//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_Final_Sistema_Reservaciones.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PV_ProyectoFinalEntities : DbContext
    {
        public PV_ProyectoFinalEntities()
            : base("name=PV_ProyectoFinalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<spConsultar_Bitacora_Result> spConsultar_Bitacora(Nullable<int> id_Reservacion)
        {
            var id_ReservacionParameter = id_Reservacion.HasValue ?
                new ObjectParameter("id_Reservacion", id_Reservacion) :
                new ObjectParameter("id_Reservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Bitacora_Result>("spConsultar_Bitacora", id_ReservacionParameter);
        }
    
        public virtual ObjectResult<spConsultar_Habitaciones_Result> spConsultar_Habitaciones()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Habitaciones_Result>("spConsultar_Habitaciones");
        }
    
        public virtual ObjectResult<spConsultar_Habitaciones_Id_Result> spConsultar_Habitaciones_Id(Nullable<int> id_Habitacion)
        {
            var id_HabitacionParameter = id_Habitacion.HasValue ?
                new ObjectParameter("id_Habitacion", id_Habitacion) :
                new ObjectParameter("id_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Habitaciones_Id_Result>("spConsultar_Habitaciones_Id", id_HabitacionParameter);
        }
    
        public virtual ObjectResult<spConsultar_Hoteles_Result> spConsultar_Hoteles()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Hoteles_Result>("spConsultar_Hoteles");
        }
    
        public virtual ObjectResult<spConsultar_Hoteles_Id_Result> spConsultar_Hoteles_Id(Nullable<int> id_Hotel)
        {
            var id_HotelParameter = id_Hotel.HasValue ?
                new ObjectParameter("id_Hotel", id_Hotel) :
                new ObjectParameter("id_Hotel", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Hoteles_Id_Result>("spConsultar_Hoteles_Id", id_HotelParameter);
        }
    
        public virtual ObjectResult<spConsultar_Mis_Reservaciones_Result> spConsultar_Mis_Reservaciones(Nullable<int> id_Persona)
        {
            var id_PersonaParameter = id_Persona.HasValue ?
                new ObjectParameter("id_Persona", id_Persona) :
                new ObjectParameter("id_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Mis_Reservaciones_Result>("spConsultar_Mis_Reservaciones", id_PersonaParameter);
        }
    
        public virtual ObjectResult<spConsultar_Reservaciones_ID_Result> spConsultar_Reservaciones_ID(Nullable<int> id_Reservacion)
        {
            var id_ReservacionParameter = id_Reservacion.HasValue ?
                new ObjectParameter("id_Reservacion", id_Reservacion) :
                new ObjectParameter("id_Reservacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Reservaciones_ID_Result>("spConsultar_Reservaciones_ID", id_ReservacionParameter);
        }
    
        public virtual ObjectResult<spConsultar_Usuarios_Result> spConsultar_Usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spConsultar_Usuarios_Result>("spConsultar_Usuarios");
        }
    
        public virtual int spCrear_Bitacora(Nullable<int> id_Reservacion, Nullable<int> id_Persona, string accion, Nullable<System.DateTime> fecha)
        {
            var id_ReservacionParameter = id_Reservacion.HasValue ?
                new ObjectParameter("id_Reservacion", id_Reservacion) :
                new ObjectParameter("id_Reservacion", typeof(int));
    
            var id_PersonaParameter = id_Persona.HasValue ?
                new ObjectParameter("id_Persona", id_Persona) :
                new ObjectParameter("id_Persona", typeof(int));
    
            var accionParameter = accion != null ?
                new ObjectParameter("Accion", accion) :
                new ObjectParameter("Accion", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrear_Bitacora", id_ReservacionParameter, id_PersonaParameter, accionParameter, fechaParameter);
        }
    
        public virtual int spCrear_Habitacion(Nullable<int> id_Hotel, string numero_Hotel, Nullable<int> capacidad_Max, string descripcion, string estado)
        {
            var id_HotelParameter = id_Hotel.HasValue ?
                new ObjectParameter("id_Hotel", id_Hotel) :
                new ObjectParameter("id_Hotel", typeof(int));
    
            var numero_HotelParameter = numero_Hotel != null ?
                new ObjectParameter("numero_Hotel", numero_Hotel) :
                new ObjectParameter("numero_Hotel", typeof(string));
    
            var capacidad_MaxParameter = capacidad_Max.HasValue ?
                new ObjectParameter("Capacidad_Max", capacidad_Max) :
                new ObjectParameter("Capacidad_Max", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spCrear_Habitacion", id_HotelParameter, numero_HotelParameter, capacidad_MaxParameter, descripcionParameter, estadoParameter);
        }
    
        public virtual ObjectResult<spCrear_Reservacion_Result> spCrear_Reservacion(Nullable<int> numPersonas, Nullable<int> idHotel, Nullable<int> idPersona, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida, Nullable<int> numeroAdultos, Nullable<int> numeroNinhos, Nullable<int> totalDiasReservacion, Nullable<decimal> costoPorCadaAdulto, Nullable<decimal> costoPorCadaNinho, Nullable<decimal> costoTotal, Nullable<System.DateTime> fechaCreacion, string estado)
        {
            var numPersonasParameter = numPersonas.HasValue ?
                new ObjectParameter("numPersonas", numPersonas) :
                new ObjectParameter("numPersonas", typeof(int));
    
            var idHotelParameter = idHotel.HasValue ?
                new ObjectParameter("idHotel", idHotel) :
                new ObjectParameter("idHotel", typeof(int));
    
            var idPersonaParameter = idPersona.HasValue ?
                new ObjectParameter("idPersona", idPersona) :
                new ObjectParameter("idPersona", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            var numeroAdultosParameter = numeroAdultos.HasValue ?
                new ObjectParameter("numeroAdultos", numeroAdultos) :
                new ObjectParameter("numeroAdultos", typeof(int));
    
            var numeroNinhosParameter = numeroNinhos.HasValue ?
                new ObjectParameter("numeroNinhos", numeroNinhos) :
                new ObjectParameter("numeroNinhos", typeof(int));
    
            var totalDiasReservacionParameter = totalDiasReservacion.HasValue ?
                new ObjectParameter("totalDiasReservacion", totalDiasReservacion) :
                new ObjectParameter("totalDiasReservacion", typeof(int));
    
            var costoPorCadaAdultoParameter = costoPorCadaAdulto.HasValue ?
                new ObjectParameter("costoPorCadaAdulto", costoPorCadaAdulto) :
                new ObjectParameter("costoPorCadaAdulto", typeof(decimal));
    
            var costoPorCadaNinhoParameter = costoPorCadaNinho.HasValue ?
                new ObjectParameter("costoPorCadaNinho", costoPorCadaNinho) :
                new ObjectParameter("costoPorCadaNinho", typeof(decimal));
    
            var costoTotalParameter = costoTotal.HasValue ?
                new ObjectParameter("costoTotal", costoTotal) :
                new ObjectParameter("costoTotal", typeof(decimal));
    
            var fechaCreacionParameter = fechaCreacion.HasValue ?
                new ObjectParameter("fechaCreacion", fechaCreacion) :
                new ObjectParameter("fechaCreacion", typeof(System.DateTime));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCrear_Reservacion_Result>("spCrear_Reservacion", numPersonasParameter, idHotelParameter, idPersonaParameter, fechaEntradaParameter, fechaSalidaParameter, numeroAdultosParameter, numeroNinhosParameter, totalDiasReservacionParameter, costoPorCadaAdultoParameter, costoPorCadaNinhoParameter, costoTotalParameter, fechaCreacionParameter, estadoParameter);
        }
    
        public virtual int spEditar_Habitacion(Nullable<int> id_Habitacion, string numero_Habitacion, Nullable<int> capacidad_Maxima, string descripcion)
        {
            var id_HabitacionParameter = id_Habitacion.HasValue ?
                new ObjectParameter("id_Habitacion", id_Habitacion) :
                new ObjectParameter("id_Habitacion", typeof(int));
    
            var numero_HabitacionParameter = numero_Habitacion != null ?
                new ObjectParameter("Numero_Habitacion", numero_Habitacion) :
                new ObjectParameter("Numero_Habitacion", typeof(string));
    
            var capacidad_MaximaParameter = capacidad_Maxima.HasValue ?
                new ObjectParameter("Capacidad_Maxima", capacidad_Maxima) :
                new ObjectParameter("Capacidad_Maxima", typeof(int));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("Descripcion", descripcion) :
                new ObjectParameter("Descripcion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditar_Habitacion", id_HabitacionParameter, numero_HabitacionParameter, capacidad_MaximaParameter, descripcionParameter);
        }
    
        public virtual int spEditar_Reservacion(Nullable<int> id_Reservacion, Nullable<System.DateTime> fechaEntrada, Nullable<System.DateTime> fechaSalida, Nullable<int> numeroAdultos, Nullable<int> numeroNinhos, Nullable<int> totalDiasReservacion, Nullable<decimal> costoTotal, Nullable<System.DateTime> fechaModificacion)
        {
            var id_ReservacionParameter = id_Reservacion.HasValue ?
                new ObjectParameter("id_Reservacion", id_Reservacion) :
                new ObjectParameter("id_Reservacion", typeof(int));
    
            var fechaEntradaParameter = fechaEntrada.HasValue ?
                new ObjectParameter("fechaEntrada", fechaEntrada) :
                new ObjectParameter("fechaEntrada", typeof(System.DateTime));
    
            var fechaSalidaParameter = fechaSalida.HasValue ?
                new ObjectParameter("fechaSalida", fechaSalida) :
                new ObjectParameter("fechaSalida", typeof(System.DateTime));
    
            var numeroAdultosParameter = numeroAdultos.HasValue ?
                new ObjectParameter("numeroAdultos", numeroAdultos) :
                new ObjectParameter("numeroAdultos", typeof(int));
    
            var numeroNinhosParameter = numeroNinhos.HasValue ?
                new ObjectParameter("numeroNinhos", numeroNinhos) :
                new ObjectParameter("numeroNinhos", typeof(int));
    
            var totalDiasReservacionParameter = totalDiasReservacion.HasValue ?
                new ObjectParameter("totalDiasReservacion", totalDiasReservacion) :
                new ObjectParameter("totalDiasReservacion", typeof(int));
    
            var costoTotalParameter = costoTotal.HasValue ?
                new ObjectParameter("costoTotal", costoTotal) :
                new ObjectParameter("costoTotal", typeof(decimal));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEditar_Reservacion", id_ReservacionParameter, fechaEntradaParameter, fechaSalidaParameter, numeroAdultosParameter, numeroNinhosParameter, totalDiasReservacionParameter, costoTotalParameter, fechaModificacionParameter);
        }
    
        public virtual int spEliminar_Reservacion(Nullable<int> id_Reservacion, string estado, Nullable<System.DateTime> fechaModificacion)
        {
            var id_ReservacionParameter = id_Reservacion.HasValue ?
                new ObjectParameter("id_Reservacion", id_Reservacion) :
                new ObjectParameter("id_Reservacion", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            var fechaModificacionParameter = fechaModificacion.HasValue ?
                new ObjectParameter("fechaModificacion", fechaModificacion) :
                new ObjectParameter("fechaModificacion", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spEliminar_Reservacion", id_ReservacionParameter, estadoParameter, fechaModificacionParameter);
        }
    
        public virtual ObjectResult<spFiltro_Gestionar_Reservaciones_Result> spFiltro_Gestionar_Reservaciones(string nombre_Persona, Nullable<System.DateTime> fecha_Entrada, Nullable<System.DateTime> fecha_Salida)
        {
            var nombre_PersonaParameter = nombre_Persona != null ?
                new ObjectParameter("Nombre_Persona", nombre_Persona) :
                new ObjectParameter("Nombre_Persona", typeof(string));
    
            var fecha_EntradaParameter = fecha_Entrada.HasValue ?
                new ObjectParameter("Fecha_Entrada", fecha_Entrada) :
                new ObjectParameter("Fecha_Entrada", typeof(System.DateTime));
    
            var fecha_SalidaParameter = fecha_Salida.HasValue ?
                new ObjectParameter("Fecha_Salida", fecha_Salida) :
                new ObjectParameter("Fecha_Salida", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spFiltro_Gestionar_Reservaciones_Result>("spFiltro_Gestionar_Reservaciones", nombre_PersonaParameter, fecha_EntradaParameter, fecha_SalidaParameter);
        }
    
        public virtual ObjectResult<spGestionar_Reservaciones_ID_Result> spGestionar_Reservaciones_ID(Nullable<int> id_Persona)
        {
            var id_PersonaParameter = id_Persona.HasValue ?
                new ObjectParameter("id_Persona", id_Persona) :
                new ObjectParameter("id_Persona", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGestionar_Reservaciones_ID_Result>("spGestionar_Reservaciones_ID", id_PersonaParameter);
        }
    
        public virtual int spInactivar_Habitacion(Nullable<int> id_Habitacion, string estado)
        {
            var id_HabitacionParameter = id_Habitacion.HasValue ?
                new ObjectParameter("id_Habitacion", id_Habitacion) :
                new ObjectParameter("id_Habitacion", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("Estado", estado) :
                new ObjectParameter("Estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spInactivar_Habitacion", id_HabitacionParameter, estadoParameter);
        }
    
        public virtual ObjectResult<spLogin_Result> spLogin(string email, string clave)
        {
            var emailParameter = email != null ?
                new ObjectParameter("Email", email) :
                new ObjectParameter("Email", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("Clave", clave) :
                new ObjectParameter("Clave", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLogin_Result>("spLogin", emailParameter, claveParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> spObtener_Id_Reservacion_Creada()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("spObtener_Id_Reservacion_Creada");
        }
    
        public virtual ObjectResult<spValidar_Habitaciones_Result> spValidar_Habitaciones(Nullable<int> id_Hotel, Nullable<int> cantidad_Personas)
        {
            var id_HotelParameter = id_Hotel.HasValue ?
                new ObjectParameter("id_Hotel", id_Hotel) :
                new ObjectParameter("id_Hotel", typeof(int));
    
            var cantidad_PersonasParameter = cantidad_Personas.HasValue ?
                new ObjectParameter("Cantidad_Personas", cantidad_Personas) :
                new ObjectParameter("Cantidad_Personas", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spValidar_Habitaciones_Result>("spValidar_Habitaciones", id_HotelParameter, cantidad_PersonasParameter);
        }
    
        public virtual ObjectResult<spValidar_Habitaciones_Reservaciones_Result> spValidar_Habitaciones_Reservaciones(Nullable<int> id_Habitacion)
        {
            var id_HabitacionParameter = id_Habitacion.HasValue ?
                new ObjectParameter("id_Habitacion", id_Habitacion) :
                new ObjectParameter("id_Habitacion", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spValidar_Habitaciones_Reservaciones_Result>("spValidar_Habitaciones_Reservaciones", id_HabitacionParameter);
        }
    
        public virtual ObjectResult<spValidar_Reservaciones_Persona_Result> spValidar_Reservaciones_Persona(Nullable<int> id_Reservacion, string nombre_Usuario)
        {
            var id_ReservacionParameter = id_Reservacion.HasValue ?
                new ObjectParameter("id_Reservacion", id_Reservacion) :
                new ObjectParameter("id_Reservacion", typeof(int));
    
            var nombre_UsuarioParameter = nombre_Usuario != null ?
                new ObjectParameter("Nombre_Usuario", nombre_Usuario) :
                new ObjectParameter("Nombre_Usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spValidar_Reservaciones_Persona_Result>("spValidar_Reservaciones_Persona", id_ReservacionParameter, nombre_UsuarioParameter);
        }
    }
}
